//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwitterPgSqlClone.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class post
    {
        public string author { get; set; }
        public string text { get; set; }
        public int id { get; set; }
    }
}
